Repository tari-project/tari-explorer, pull requests merged in 2024-02, with the labels that each got.

#24 feat: add cache settings
  routes/blocks.js
  routes/mempool.js
  routes/search_commitments.js
  routes/search_kernels.js
Labels: P-reviews_required

#25 feat: healthz page
  app.js
  routes/healthz.js
  views/healthz.hbs
Labels: P-reviews_required

#27 fix: tip
  routes/blocks.js
  routes/index.js
  views/index.hbs
Labels: P-reviews_required

#28 feat: add favicons
  .dockerignore
  .gitignore
  app.js
  package-lock.json
  package.json
  public/favicon.ico
  public/favicon.png
  public/favicon.svg
Labels: CR-too_long, P-acks_required

#26 feat: add lru cache and block info pagination
  app.js
  cache.js
  routes/blocks.js
  views/blocks.hbs
Labels: P-reviews_required

#31 feat: read cache settings from env var
  cacheSettings.js
  routes/assets.js
  routes/blocks.js
  routes/index.js
  routes/mempool.js
  routes/search_commitments.js
  routes/search_kernels.js
Labels: P-reviews_required

#32 feat: add simpler block data pagination
  app.js
  routes/block_data.js
Labels: P-acks_required
