Repository tari-project/tari-explorer, pull requests merged in 2025-05, with the labels that each got.

#55 feat: add block statistics
  README.md
  app.js
  cache.js
  package-lock.json
  routes/blocks.js
  routes/index.js
  routes/stats.js
  utils/stats.js
  views/blocks.hbs
  views/index.hbs
  views/stats.hbs
Labels: P-acks_required

#58 chore(ci): move scheduled builds to weekly
  .github/workflows/build_docker.yml
Labels: CR-insufficient_context

#61 chore(ci): correct branch vs tag refs
  .github/workflows/build_docker.yml
Labels: CR-insufficient_context

#62 chore(ci): fix typo and maybe better flow
  .github/workflows/build_docker.yml
Labels: CR-insufficient_context

#63 chore(ci): update to be able to pull protos from tagged release
  .github/workflows/build_docker.yml
  routes/mempool.js
  views/mempool.hbs
Labels: CR-insufficient_context

#66 feat: additions and fixes
  app.js
  baseNodeClient.js
  routes/index.js
  routes/mempool.js
  routes/miners.js
  routes/stats.js
  utils/stats.js
  views/index.hbs
  views/mempool.hbs
  views/stats.hbs
Labels: P-acks_required

#39 fix: fix broken protos
  applications/minotari_app_grpc/proto/base_node.proto
Labels: CR-insufficient_context

#67 chore(fix): update miner to return http cached headers and fix proto usage
  routes/miners.js
Labels: P-acks_required

#69 fix: adds tip height to blocks cache for second request to listHeaders
  routes/index.js
Labels: P-acks_required, P-reviews_required
