Repository tari-project/tari-explorer, pull requests merged in 2025-06, with the labels that each got.

#79 feat: add ts support
  .gitignore
  .prettierignore
  Dockerfile
  README.md
  app.ts
  baseNodeClient.js
  baseNodeClient.ts
  bin/www
  cache.ts
  cacheSettings.ts
  eslint.config.js
  index.ts
  package-lock.json
  package.json
  routes/assets.ts
  routes/block_data.ts
  routes/blocks.ts
  routes/export.js
  routes/export.ts
  routes/healthz.ts
  routes/index.ts
  routes/mempool.js
  routes/mempool.ts
  routes/miners.ts
  routes/search_commitments.ts
  routes/search_kernels.ts
  script.ts
  tsconfig.json
  utils/stats.js
  utils/stats.ts
  utils/updater.ts
Labels: CR-too_long, P-acks_required

#86 fix: attempt to fix docker
  Dockerfile
Labels: P-acks_required, P-reviews_required

#90 feat: add proto type gen with refresh
  .gitignore
  .prettierignore
  README.md
  app.ts
  applications/minotari_app_grpc/proto/base_node.proto
  applications/minotari_app_grpc/proto/wallet.proto
  baseNodeClient.ts
  bin/execGrpcGeneration.ts
  bin/refreshGrpcFiles.ts
  cache.ts
  index.ts
  package-lock.json
  package.json
  routes/assets.ts
  routes/block_data.ts
  routes/blocks.ts
  routes/export.ts
  routes/index.ts
  routes/mempool.ts
  routes/miners.ts
  routes/search_commitments.ts
  routes/search_kernels.ts
  routes/search_outputs_by_payref.ts
  utils/grpcHelpers.ts
  utils/sanitizeObject.ts
  utils/stats.ts
Labels: CR-too_long, P-acks_required, P-reviews_required
